import { writeLog } from '@/lib/db';
import { fetchTranscript } from 'youtube-transcript';

const TIMEOUT = 12000;

function extractVideoId(input) {
  if (!input) return '';
  const s = String(input).trim();
  if (/^[\w-]{11}$/.test(s)) return s;
  const m1 = s.match(/[?&]v=([\w-]{11})/);
  if (m1) return m1[1];
  const m2 = s.match(/youtu\.be\/([\w-]{11})/);
  if (m2) return m2[1];
  const m3 = s.match(/\/shorts\/([\w-]{11})/);
  if (m3) return m3[1];
  return s;
}

function parseVtt(vtt) {
  if (!vtt) return '';
  return vtt
    .split('\n')
    .filter(l => l && !/^WEBVTT/.test(l) && !/^NOTE\b/.test(l) && !/^\d+$/.test(l.trim()) && !l.includes('-->'))
    .join(' ')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&#39;/g, "'")
    .replace(/&quot;/g, '"')
    .replace(/\s+/g, ' ')
    .trim();
}

function pickBestSubtitle(subs) {
  if (!Array.isArray(subs) || subs.length === 0) return null;
  const en = subs.find(s => s?.code?.startsWith('en'));
  if (en?.url) return en;
  const auto = subs.find(s => s?.autoGenerated && s?.url);
  if (auto?.url) return auto;
  const withUrl = subs.find(s => s?.url);
  return withUrl || null;
}

async function tryYoutubeTranscript(videoId) {
  try {
    const segments = await fetchTranscript(videoId);
    if (segments && segments.length > 0) {
      const text = segments.map(s => s.text).join(' ').replace(/\s+/g, ' ').trim();
      if (text && text.length > 20) {
        return { source: 'youtube-transcript:innertube', text, lang: segments[0]?.lang || 'auto' };
      }
    }
  } catch (e) {
    const msg = e?.message || '';
    if (msg.includes('disabled')) return { disabled: true };
    if (msg.includes('unavailable') || msg.includes('no longer available')) return { unavailable: true };
    if (msg.includes('not available')) {
      if (msg.includes('language')) return { langUnavailable: true };
      return { notAvailable: true };
    }
    if (msg.includes('too many')) return { rateLimited: true };
  }
  return null;
}

const PIPED_INSTANCES = [
  'https://pipedapi.kavin.rocks',
  'https://pipedapi.adminforge.de',
  'https://api.piped.projectsegfau.lt',
  'https://pipedapi.r4fo.com',
  'https://piped-api.privacy.com.de',
  'https://pipedapi.darkness.services',
  'https://pipedapi.osphost.fi',
];

const INVIDIOUS_INSTANCES = [
  'https://inv.nadeko.net',
  'https://yewtu.be',
  'https://invidious.privacyredirect.com',
  'https://invidious.fdn.fr',
  'https://invidious.protokolla.fi',
  'https://invidious.nerdvpn.de',
  'https://vid.puffyan.us',
  'https://invidious.materialio.us',
];

async function fetchText(url) {
  const res = await fetch(url, {
    signal: AbortSignal.timeout(TIMEOUT),
    headers: { 'User-Agent': 'Mozilla/5.0 (compatible; ChafiktechBot/1.0)' }
  });
  if (!res.ok) return null;
  return await res.text();
}

async function tryPiped(videoId) {
  for (const inst of PIPED_INSTANCES) {
    try {
      const res = await fetch(`${inst}/streams/${videoId}`, {
        signal: AbortSignal.timeout(TIMEOUT),
        headers: { 'User-Agent': 'Mozilla/5.0' }
      });
      if (!res.ok) continue;
      const data = await res.json();
      const sub = pickBestSubtitle(data?.subtitles);
      if (sub?.url) {
        const vtt = await fetchText(sub.url);
        const text = parseVtt(vtt);
        if (text && text.length > 20) {
          return { source: `piped:${inst.replace('https://', '')}`, text, lang: sub.code || 'auto' };
        }
      }
    } catch {
      continue;
    }
  }
  return null;
}

async function tryInvidious(videoId) {
  for (const inst of INVIDIOUS_INSTANCES) {
    try {
      const apiUrl = `${inst}/api/v1/captions/${videoId}`;
      const res = await fetch(apiUrl, {
        signal: AbortSignal.timeout(TIMEOUT),
        headers: { 'User-Agent': 'Mozilla/5.0' }
      });
      if (!res.ok) continue;
      const data = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        const cap = data.find(c => !c?.name || c?.name?.toLowerCase?.().includes('en'))
          || data.find(c => c?.name?.toLowerCase?.().includes('auto') || c?.name?.toLowerCase?.().includes('orig'))
          || data[0];
        const url = typeof cap === 'object' ? cap.url : null;
        if (url) {
          const fullUrl = url.startsWith('/') ? inst + url : url;
          const vtt = await fetchText(fullUrl);
          const text = parseVtt(vtt);
          if (text && text.length > 20) {
            return { source: `invidious:${inst.replace('https://', '')}`, text, lang: cap?.language_code || cap?.name || 'auto' };
          }
        }
      }
    } catch {
      continue;
    }
  }
  return null;
}

async function tryYoutubeTimedtext(videoId) {
  const langs = ['en', 'en-US', 'en-GB', 'a.en'];
  for (const lang of langs) {
    try {
      const url = `https://www.youtube.com/api/timedtext?v=${videoId}&lang=${lang}&fmt=vtt&kind=asr`;
      const vtt = await fetchText(url);
      const text = parseVtt(vtt);
      if (text && text.length > 20) {
        return { source: 'youtube:timedtext', text, lang };
      }
    } catch {
      continue;
    }
  }
  return null;
}

export async function POST(request) {
  let body;
  try { body = await request.json(); } catch {
    return Response.json({ success: false, message: 'Invalid JSON body' }, { status: 400 });
  }

  const videoId = extractVideoId(body?.videoId || body?.url);
  if (!videoId || videoId.length !== 11) {
    return Response.json(
      { success: false, message: 'Invalid YouTube URL or video ID.' },
      { status: 400 }
    );
  }

  let result = null;
  const sources = [];

  // Primary: youtube-transcript package (InnerTube API)
  sources.push('youtube-transcript');
  result = await tryYoutubeTranscript(videoId);

  // If the video exists but has no transcript, skip fallbacks
  if (result && result.notAvailable) {
    try { await writeLog('WARN', 'Transcript not available for video', { videoId }); } catch {}
    return Response.json({
      success: false,
      message: `This video (${videoId}) has no transcript available. The video may have captions disabled. Please paste the transcript text manually.`
    }, { status: 404 });
  }

  if (result && result.disabled) {
    try { await writeLog('WARN', 'Transcript disabled for video', { videoId }); } catch {}
    return Response.json({
      success: false,
      message: `Transcript is disabled for this video (${videoId}). Please paste the transcript text manually.`
    }, { status: 404 });
  }

  if (!result) {
    // Fallback 1: Piped
    sources.push('Piped');
    result = await tryPiped(videoId);
  }

  if (!result) {
    // Fallback 2: Invidious
    sources.push('Invidious');
    result = await tryInvidious(videoId);
  }

  if (!result) {
    // Fallback 3: YouTube timedtext
    sources.push('YouTube timedtext');
    result = await tryYoutubeTimedtext(videoId);
  }

  if (!result) {
    try {
      await writeLog('WARN', 'Transcript fetch failed for video', { videoId, tried: sources.join(',') });
    } catch {}
    return Response.json({
      success: false,
      message: `Could not fetch transcript for video ${videoId} from any of ${sources.length} sources. Possible reasons: (1) the video has no captions/subtitles, (2) the video is private, age-restricted, or region-locked, (3) all public transcript APIs are currently down. Please paste the transcript text manually in the textarea below.`
    }, { status: 404 });
  }

  try {
    await writeLog('INFO', 'Transcript fetched', { videoId, source: result.source, length: result.text.length });
  } catch {}

  return Response.json({
    success: true,
    videoId,
    transcript: result.text,
    source: result.source,
    lang: result.lang || 'auto',
    length: result.text.length
  });
}

export async function GET() {
  return Response.json({
    service: 'YouTube Transcript Fetcher',
    version: '2.0',
    usage: 'POST { videoId: "<11-char id>" } or POST { url: "<youtube url>" }'
  });
}
