-- lib/auto-publisher/migrate.sql
-- Run this once on your Supabase database to ensure all required columns exist
-- Safe to run multiple times (uses IF NOT EXISTS)

ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS meta_title TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS keywords TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS faqs JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS faq_schema JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS featured_image TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS author TEXT DEFAULT 'Chafiktech AI';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS trend_title TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS seo_score INTEGER;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS word_count INTEGER;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS excerpt TEXT;

-- Index for faster queries
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_source ON blog_posts(source);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);

-- Comment for documentation
COMMENT ON TABLE blog_posts IS 'Blog posts - can be created manually, via admin panel, or auto-generated by /api/cron/daily-publisher';
