-- lib/auto-publisher/migrate.sql
-- Run this once on your Supabase database to ensure all required columns exist
-- Safe to run multiple times (uses IF NOT EXISTS)

-- Core content
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS meta_title TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS meta_description TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS keywords TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS category TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS tags JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS faqs JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS faq_schema JSONB;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS featured_image TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS author TEXT DEFAULT 'Chafiktech AI';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'manual';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS trend_title TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS seo_score INTEGER;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS word_count INTEGER;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS excerpt TEXT;

-- New: multilingual + richer SEO fields
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS base_slug TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS locale TEXT DEFAULT 'en';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS primary_keyword TEXT DEFAULT '';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS secondary_keywords JSONB DEFAULT '[]';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS long_tail_keywords JSONB DEFAULT '[]';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS related_search_terms JSONB DEFAULT '[]';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS hashtags TEXT DEFAULT '';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS key_facts JSONB DEFAULT '[]';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS key_takeaways JSONB DEFAULT '[]';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS article_schema JSONB DEFAULT NULL;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS image_prompt TEXT DEFAULT '';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS model TEXT DEFAULT NULL;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS reading_time INTEGER DEFAULT 5;

-- Indexes for faster queries
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_source ON blog_posts(source);
CREATE INDEX IF NOT EXISTS idx_blog_posts_slug ON blog_posts(slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_base_slug ON blog_posts(base_slug);
CREATE INDEX IF NOT EXISTS idx_blog_posts_locale ON blog_posts(locale);
CREATE INDEX IF NOT EXISTS idx_blog_posts_created_at ON blog_posts(created_at DESC);

-- Comment for documentation
COMMENT ON TABLE blog_posts IS 'Blog posts - can be created manually, via admin panel, or auto-generated by /api/cron/daily-publisher. Multilingual rows share a base_slug with a per-row locale suffix (-en, -ar, -fr).';
